# Generated by Django 3.1.1 on 2020-09-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='group',
        ),
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
    ]
