# Generated by Django 3.1.1 on 2020-09-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200916_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_user',
        ),
    ]
