# Generated by Django 3.1.1 on 2020-09-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20200917_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
